export const UPDATE_FILTER_MONTH = 'UPDATE_FILTER_MONTH'
export const UPDATE_FILTER_CATEGORY = 'UPDATE_FILTER_CATEGORY'
export const UPDATE_SORTER_AMOUNT = 'UPDATE_SORTER_AMOUNT'
export const APPEND_NEW_BILL = 'APPEND_NEW_BILL'
